all: program1 program2 program3

program1: client.c
	gcc client.c -o client -Wall -pthread

program2: serverY.c
	gcc serverY.c -o serverY -Wall -pthread

program3: serverZ.c
	gcc serverZ.c -o serverZ -Wall -pthread
